### ISSUE TITLE
Use OS definition of tiles

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/abstreet-to-atip#2]
Looking at this based on previous code: https://github.com/saferactive/saferactive/blob/master/code/tests/ltn-analysis.R

**Comment by dabreegster** [comment]
https://raw.githubusercontent.com/charlesroper/OSGB_Grids/master/GeoJSON/OSGB_Grid_1km.geojson is way too small. Looks like the thing I did before is 0.01 degrees

**Comment by dabreegster** [comment]
https://github.com/charlesroper/OSGB_Grids/tree/master/GeoJSON has other sizes. 10km looks good to start with. Thanks!
